// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import Navbar from '../components/Navbar'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>News App</title>
//         {/* <meta name="description" content="Generated by create next app" /> */}
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Navbar/>
//       <main className={styles.main}>
//         {/* <h1> Home Page </h1> */}
//         <p>Homepage content here</p>
//       </main>
//     </div>
//   )
// }

import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <center>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, harum. Fuga optio ipsum reiciendis facere sit modi doloribus commodi consectetur.
        </p></center>
    </div>
  )
}